// packages/react/src/components/TuxBetaRibbon.tsx
/**
 * TuxBetaRibbon — environment / lifecycle label that signals
 * "this isn't the production deploy".
 * React port of app/components/TuxBetaRibbon.vue.
 */

import React, { forwardRef, type HTMLAttributes, type ReactNode } from "react";
import "./tux-beta-ribbon.css";

export type TuxBetaRibbonVariant = "corner" | "stripe" | "pill";
export type TuxBetaRibbonKind = "preview" | "beta" | "dev";
export type TuxBetaRibbonCorner = "top-right" | "top-left" | "bottom-right" | "bottom-left";

export interface TuxBetaRibbonProps extends HTMLAttributes<HTMLElement> {
  variant?: TuxBetaRibbonVariant;
  kind?: TuxBetaRibbonKind;
  /** Custom label text. Defaults vary by kind. */
  label?: string;
  /** Where the corner ribbon sits. Only applies to variant="corner". */
  corner?: TuxBetaRibbonCorner;
  /** Stripe message. Only applies to variant="stripe". */
  message?: string;
  children?: ReactNode;
}

const defaultLabel: Record<TuxBetaRibbonKind, string> = {
  preview: "preview",
  beta: "beta",
  dev: "dev",
};

const defaultMessage: Record<TuxBetaRibbonKind, string> = {
  preview: "Preview environment — data may differ from production.",
  beta: "This is a public beta. Feedback welcome at support@tti.tamu.edu.",
  dev: "Non-production environment. Do not enter real research data.",
};

export const TuxBetaRibbon = forwardRef<HTMLElement, TuxBetaRibbonProps>(
  function TuxBetaRibbon(
    {
      variant = "corner",
      kind = "preview",
      label,
      corner = "top-right",
      message,
      children,
      className = "",
      ...restProps
    },
    ref,
  ) {
    const resolvedLabel = label ?? defaultLabel[kind];
    const resolvedMessage = message ?? defaultMessage[kind];

    if (variant === "corner") {
      return (
        <div
          ref={ref as React.Ref<HTMLDivElement>}
          className={`tux-beta-corner tux-beta-corner--${corner} tux-beta--${kind} ${className}`.trim()}
          role="note"
          aria-label={`Environment: ${resolvedLabel}`}
          {...(restProps as HTMLAttributes<HTMLDivElement>)}
        >
          <span className="tux-beta-corner__band">{resolvedLabel}</span>
        </div>
      );
    }

    if (variant === "stripe") {
      return (
        <aside
          ref={ref as React.Ref<HTMLElement>}
          className={`tux-beta-stripe tux-beta--${kind} ${className}`.trim()}
          role="note"
          aria-label={`Environment: ${resolvedLabel}`}
          {...(restProps as HTMLAttributes<HTMLElement>)}
        >
          <span className="tux-beta-stripe__pill">{resolvedLabel}</span>
          <span className="tux-beta-stripe__message">
            {children || resolvedMessage}
          </span>
        </aside>
      );
    }

    // variant === "pill"
    return (
      <span
        ref={ref as React.Ref<HTMLSpanElement>}
        className={`tux-beta-pill tux-beta--${kind} ${className}`.trim()}
        role="note"
        aria-label={`Status: ${resolvedLabel}`}
        {...(restProps as HTMLAttributes<HTMLSpanElement>)}
      >
        {kind === "dev" && (
          <svg
            className="tux-beta-pill__icon"
            aria-hidden="true"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M7 18v-6a5 5 0 1 1 10 0v6" />
            <path d="M5 21h14" />
            <path d="M21 12h1" />
            <path d="M18.5 4.5 19 4" />
            <path d="M2 12h1" />
            <path d="M12 2v1" />
            <path d="m4.929 4.929.707.707" />
            <path d="M12 12v6" />
          </svg>
        )}
        <span className="tux-beta-pill__dot" aria-hidden="true" />
        {resolvedLabel}
      </span>
    );
  },
);

// app/components/TuxBetaRibbon.vue
<script setup lang="ts">
/**
 * TuxBetaRibbon — environment / lifecycle label that signals
 * "this isn't the production deploy". Use for preview environments,
 * non-production deployments, beta features, sandboxes, demos.
 *
 * Three variants — pick by host context, not aesthetic preference:
 *
 *   1. `variant="corner"` — diagonal ribbon in the page corner
 *      (top-right by default). Eye-catching, hard to miss.
 *      Right reach for: full-deploy preview environments
 *      (preview.tti.tamu.edu), staging, demo seats.
 *
 *   2. `variant="stripe"` — top-of-page horizontal stripe, full-width.
 *      Right reach for: production-shaped deploys with non-prod data
 *      (a real-feeling demo with seeded fixtures), or lifecycle
 *      labels on the canonical product (a public beta).
 *
 *   3. `variant="pill"` — inline pill, flows in normal page chrome.
 *      Right reach for: feature-level beta tags ("This dashboard is
 *      in beta"), per-page indicators, headers and breadcrumbs.
 *
 * Tones:
 *   - `preview` (default · gold) — preview / staging.
 *   - `beta` (navy) — public beta / new feature.
 *   - `dev` (warning red) — non-production / sandbox.
 *
 * For maintenance windows, prefer `TuxAnnouncementBanner tone="urgent"` —
 * that's a content notice, not a chrome label.
 */
type Variant = "corner" | "stripe" | "pill";
type Kind = "preview" | "beta" | "dev";
type Corner = "top-right" | "top-left" | "bottom-right" | "bottom-left";

interface Props {
  variant?: Variant;
  kind?: Kind;
  /** Custom label text. Defaults vary by kind. */
  label?: string;
  /** Where the corner ribbon sits. Only applies to `variant="corner"`. */
  corner?: Corner;
  /** Stripe message. Only applies to `variant="stripe"`. */
  message?: string;
}

const props = withDefaults(defineProps<Props>(), {
  variant: "corner",
  kind: "preview",
  label: undefined,
  corner: "top-right",
  message: undefined,
});

const defaultLabel: Record<Kind, string> = {
  preview: "preview",
  beta:    "beta",
  dev:     "dev",
};

const defaultMessage: Record<Kind, string> = {
  preview: "Preview environment — data may differ from production.",
  beta:    "This is a public beta. Feedback welcome at support@tti.tamu.edu.",
  dev:     "Non-production environment. Do not enter real research data.",
};

const resolvedLabel = computed(() => props.label ?? defaultLabel[props.kind]);
const resolvedMessage = computed(() => props.message ?? defaultMessage[props.kind]);
</script>

<template>
  <!-- Corner ribbon -->
  <div
    v-if="variant === 'corner'"
    class="tux-beta-corner"
    :class="[`tux-beta-corner--${corner}`, `tux-beta--${kind}`]"
    role="note"
    :aria-label="`Environment: ${resolvedLabel}`"
  >
    <span class="tux-beta-corner__band">{{ resolvedLabel }}</span>
  </div>

  <!-- Top stripe -->
  <aside
    v-else-if="variant === 'stripe'"
    class="tux-beta-stripe"
    :class="`tux-beta--${kind}`"
    role="note"
    :aria-label="`Environment: ${resolvedLabel}`"
  >
    <span class="tux-beta-stripe__pill">{{ resolvedLabel }}</span>
    <span class="tux-beta-stripe__message">
      <slot>{{ resolvedMessage }}</slot>
    </span>
  </aside>

  <!-- Inline pill -->
  <span
    v-else
    class="tux-beta-pill"
    :class="`tux-beta--${kind}`"
    role="note"
    :aria-label="`Status: ${resolvedLabel}`"
  >
    <UIcon
      v-if="kind === 'dev'"
      name="lucide:siren"
      class="tux-beta-pill__icon"
      aria-hidden="true"
    />
    <span class="tux-beta-pill__dot" aria-hidden="true" />
    {{ resolvedLabel }}
  </span>
</template>

<style scoped>
/* ── Tone palette (shared across variants) ──────────────────── */
.tux-beta--preview {
  --tux-beta-bg:    var(--brand-accent);
  --tux-beta-fg:    #1f1c1c;
  --tux-beta-tint:  color-mix(in srgb, var(--brand-accent) 22%, transparent);
}

.tux-beta--beta {
  --tux-beta-bg:    var(--brand-secondary);
  --tux-beta-fg:    #ffffff;
  --tux-beta-tint:  color-mix(in srgb, var(--brand-secondary) 18%, transparent);
}

.tux-beta--dev {
  --tux-beta-bg:    var(--color-error);
  --tux-beta-fg:    #ffffff;
  --tux-beta-tint:  color-mix(in srgb, var(--color-error) 18%, transparent);
}

/* ── Corner ribbon ──────────────────────────────────────────── */
.tux-beta-corner {
  position: fixed;
  z-index: 50;
  width: 8.5rem;
  height: 8.5rem;
  overflow: hidden;
  pointer-events: none;
}

.tux-beta-corner--top-right    { top: 0; right: 0; }
.tux-beta-corner--top-left     { top: 0; left: 0; }
.tux-beta-corner--bottom-right { bottom: 0; right: 0; }
.tux-beta-corner--bottom-left  { bottom: 0; left: 0; }

.tux-beta-corner__band {
  position: absolute;
  display: block;
  width: 12rem;
  padding: 0.4375rem 0;
  text-align: center;
  font-family: var(--font-mono);
  font-size: 0.7rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  background: var(--tux-beta-bg);
  color: var(--tux-beta-fg);
  box-shadow: var(--elevation-rest);
}

.tux-beta-corner--top-right .tux-beta-corner__band {
  top: 1.875rem;
  right: -3rem;
  transform: rotate(45deg);
}

.tux-beta-corner--top-left .tux-beta-corner__band {
  top: 1.875rem;
  left: -3rem;
  transform: rotate(-45deg);
}

.tux-beta-corner--bottom-right .tux-beta-corner__band {
  bottom: 1.875rem;
  right: -3rem;
  transform: rotate(-45deg);
}

.tux-beta-corner--bottom-left .tux-beta-corner__band {
  bottom: 1.875rem;
  left: -3rem;
  transform: rotate(45deg);
}

/* ── Top stripe ─────────────────────────────────────────────── */
.tux-beta-stripe {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.4375rem 1rem;
  background: var(--tux-beta-tint);
  border-bottom: 1px solid color-mix(in srgb, var(--tux-beta-bg) 35%, transparent);
  font-size: 0.8125rem;
  color: var(--text-primary);
}

.tux-beta-stripe__pill {
  display: inline-flex;
  align-items: center;
  padding: 0.0625rem 0.4375rem;
  font-family: var(--font-mono);
  font-size: 0.6875rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  background: var(--tux-beta-bg);
  color: var(--tux-beta-fg);
  border-radius: var(--radius-sm);
  flex-shrink: 0;
}

.tux-beta-stripe__message {
  flex: 1;
  min-width: 0;
}

/* ── Inline pill ────────────────────────────────────────────── */
.tux-beta-pill {
  display: inline-flex;
  align-items: center;
  gap: 0.375rem;
  padding: 0.125rem 0.5rem;
  font-family: var(--font-mono);
  font-size: 0.7rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  background: var(--tux-beta-tint);
  color: var(--text-primary);
  border: 1px solid color-mix(in srgb, var(--tux-beta-bg) 35%, transparent);
  border-radius: var(--radius-sm);
  white-space: nowrap;
  vertical-align: middle;
}

.tux-beta-pill__dot {
  display: inline-block;
  width: 0.375rem;
  height: 0.375rem;
  border-radius: 50%;
  background: var(--tux-beta-bg);
}

.tux-beta-pill__icon {
  width: 0.8125rem;
  height: 0.8125rem;
  color: var(--tux-beta-bg);
}
</style>
