// packages/react/src/components/TuxCodeBlock.tsx
/**
 * TuxCodeBlock — standalone code block with caption, copy action, and line numbers.
 * React port of app/components/TuxCodeBlock.vue.
 */

import React, { forwardRef, useState, type HTMLAttributes } from "react";
import "./tux-code-block.css";

export interface TuxCodeBlockProps extends HTMLAttributes<HTMLElement> {
  /** Source code string. */
  code: string;
  /** Language identifier (ts, python, bash, json, etc.). */
  lang?: string;
  /** Optional caption or filename. */
  filename?: string;
  /** Show 1-indexed line numbers. */
  lineNumbers?: boolean;
  /** Hide the copy button. */
  noCopy?: boolean;
  /** Hide the download button. */
  noDownload?: boolean;
  /** Suggested download filename. */
  downloadName?: string;
  /** Pre-rendered highlighted HTML (optional Shiki/Prism output). */
  highlightedHtml?: string;
}

const LANG_EXT: Record<string, string> = {
  ts: "ts", tsx: "tsx", js: "js", jsx: "jsx", vue: "vue",
  python: "py", py: "py", rust: "rs", go: "go", java: "java",
  c: "c", cpp: "cpp", cs: "cs", rb: "rb", php: "php",
  bash: "sh", sh: "sh", zsh: "sh",
  yaml: "yml", yml: "yml", json: "json", toml: "toml",
  html: "html", css: "css", scss: "scss",
  md: "md", markdown: "md", sql: "sql", text: "txt",
};

export const TuxCodeBlock = forwardRef<HTMLElement, TuxCodeBlockProps>(
  function TuxCodeBlock(
    {
      code,
      lang = "text",
      filename,
      lineNumbers = false,
      noCopy = false,
      noDownload = false,
      downloadName,
      highlightedHtml,
      className = "",
      ...restProps
    },
    ref,
  ) {
    const [copied, setCopied] = useState(false);

    const resolvedDownloadName = (() => {
      if (downloadName) return downloadName;
      if (filename) {
        return filename.split("/").pop()!.split(":")[0]!;
      }
      const ext = LANG_EXT[lang] ?? "txt";
      return `code.${ext}`;
    })();

    const handleCopy = async () => {
      if (typeof navigator !== "undefined" && navigator.clipboard) {
        try {
          await navigator.clipboard.writeText(code);
          setCopied(true);
          setTimeout(() => setCopied(false), 2000);
        } catch {
          // ignore clipboard errors
        }
      }
    };

    const handleDownload = () => {
      if (typeof window === "undefined") return;
      const blob = new Blob([code], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = resolvedDownloadName;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    };

    const lines = code.split("\n");

    const classes = [
      "tux-codeblock",
      lineNumbers ? "tux-codeblock--with-lines" : "",
      className,
    ]
      .filter(Boolean)
      .join(" ");

    return (
      <figure ref={ref} className={classes} {...restProps}>
        {filename && (
          <figcaption className="tux-codeblock__caption">
            <span className="tux-codeblock__filename">{filename}</span>
            {lang !== "text" && <span className="tux-codeblock__lang">{lang}</span>}
          </figcaption>
        )}

        <div className="tux-codeblock__body">
          {(!noCopy || !noDownload) && (
            <div className="tux-codeblock__actions">
              {!noDownload && (
                <button
                  type="button"
                  className="tux-codeblock__action"
                  aria-label={`Download ${resolvedDownloadName}`}
                  onClick={handleDownload}
                >
                  <svg
                    className="tux-codeblock__action-icon"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    aria-hidden="true"
                  >
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                    <polyline points="7 10 12 15 17 10" />
                    <line x1="12" y1="15" x2="12" y2="3" />
                  </svg>
                  <span>Download</span>
                </button>
              )}
              {!noCopy && (
                <button
                  type="button"
                  className="tux-codeblock__action"
                  aria-label={copied ? "Copied" : "Copy code"}
                  onClick={handleCopy}
                >
                  {copied ? (
                    <svg
                      className="tux-codeblock__action-icon"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      aria-hidden="true"
                    >
                      <polyline points="20 6 9 17 4 12" />
                    </svg>
                  ) : (
                    <svg
                      className="tux-codeblock__action-icon"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      aria-hidden="true"
                    >
                      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                    </svg>
                  )}
                  <span>{copied ? "Copied" : "Copy"}</span>
                </button>
              )}
            </div>
          )}

          {highlightedHtml ? (
            <div
              className="tux-codeblock__rendered"
              dangerouslySetInnerHTML={{ __html: highlightedHtml }}
            />
          ) : (
            <pre className="tux-codeblock__fallback">
              <code>
                {lines.map((line, i) => (
                  <span key={i} className="tux-codeblock__line">
                    {lineNumbers && (
                      <span className="tux-codeblock__line-no" aria-hidden="true">
                        {i + 1}
                      </span>
                    )}
                    <span>{line}{"\n"}</span>
                  </span>
                ))}
              </code>
            </pre>
          )}
        </div>
      </figure>
    );
  },
);

// app/components/TuxCodeBlock.vue
<script setup lang="ts">
import type { BundledLanguage, BundledTheme } from "shiki";

// TuxCodeBlock — standalone Shiki-backed code block.
//
// For docs, blog posts, ADRs, anywhere users want to embed a code
// sample outside the component-demo flow (`TuxExample` covers that).
// Supports any Shiki-bundled language.
//
// **Highlighting runs at SSR time** via `useTuxHighlighter` — a
// singleton highlighter shared across every TuxCodeBlock and
// TuxExample on the page. The initial document ships with already-
// colored HTML; no flash of unhighlighted code on first paint.
// Re-highlighting on color-mode change happens client-side.

interface Props {
  /** Source code as a string. Required. */
  code: string;
  /** Shiki language id — `ts`, `python`, `bash`, `json`, `vue`, etc.
   *  Falls back to `text` (no highlighting) for unknown langs. */
  lang?: BundledLanguage | "text";
  /** Optional caption — typically a filename like
   *  `app/components/TuxButton.vue` or `landscape/agent.py:42`. */
  filename?: string;
  /** Show 1-indexed line numbers in the gutter. */
  lineNumbers?: boolean;
  /** Hide the copy button. */
  noCopy?: boolean;
  /** Hide the download button. */
  noDownload?: boolean;
  /** Override the suggested filename for downloads. Falls back to
   *  `filename` (basename) or `code.{ext}` derived from `lang`. */
  downloadName?: string;
}

const props = withDefaults(defineProps<Props>(), {
  lang: "text",
  filename: undefined,
  lineNumbers: false,
  noCopy: false,
  noDownload: false,
  downloadName: undefined,
});

const colorMode = useColorMode();
const { highlight } = useTuxHighlighter();
const copied = ref(false);

const shikiTheme = computed<BundledTheme>(() => {
  if (colorMode.value === "tti-dark") return "github-dark";
  if (colorMode.value === "tti-hc")   return "github-light-high-contrast";
  return "github-light";
});

// Highlight at SSR time + re-run when props/theme change. useAsyncData
// dedupes the work across hydration so the initial paint is already
// colored.
const cacheKey = computed(() =>
  `tux-codeblock:${props.lang}:${shikiTheme.value}:${hashCode(props.code)}`
);

const { data: highlightedCode } = await useAsyncData(
  cacheKey.value,
  () => highlight(props.code, { lang: props.lang, theme: shikiTheme.value }),
  { watch: [() => props.code, () => props.lang, shikiTheme] },
);

function hashCode(s: string): string {
  // Tiny deterministic hash — only keys the asyncData cache. A
  // collision just causes a re-highlight; correctness never depends
  // on it.
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return h.toString(36);
}

// Defensive fallback — only rendered if highlighter is somehow null
// (Shiki crashed during SSR). In practice, useAsyncData should always
// resolve to a string by paint time.
const lines = computed(() => props.code.split("\n"));

async function copy() {
  if (typeof navigator === "undefined" || !navigator.clipboard) return;
  await navigator.clipboard.writeText(props.code);
  copied.value = true;
  setTimeout(() => (copied.value = false), 1500);
}

const LANG_EXT: Record<string, string> = {
  ts: "ts", tsx: "tsx", js: "js", jsx: "jsx", vue: "vue",
  python: "py", py: "py", rust: "rs", go: "go", java: "java",
  c: "c", cpp: "cpp", cs: "cs", rb: "rb", php: "php",
  bash: "sh", sh: "sh", zsh: "sh", fish: "sh",
  yaml: "yml", yml: "yml", json: "json", toml: "toml",
  html: "html", css: "css", scss: "scss",
  md: "md", markdown: "md", sql: "sql", text: "txt",
};

const resolvedDownloadName = computed(() => {
  if (props.downloadName) return props.downloadName;
  if (props.filename) {
    // Strip any path prefix and `:line` suffix — keep just the basename.
    return props.filename.split("/").pop()!.split(":")[0]!;
  }
  const ext = LANG_EXT[props.lang] ?? "txt";
  return `code.${ext}`;
});

function download() {
  if (typeof window === "undefined") return;
  const blob = new Blob([props.code], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = resolvedDownloadName.value;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Defer revoke so the download has time to start in slower browsers.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
</script>

<template>
  <figure class="tux-codeblock" :class="{ 'tux-codeblock--with-lines': lineNumbers }">
    <figcaption v-if="filename" class="tux-codeblock__caption">
      <span class="tux-codeblock__filename">{{ filename }}</span>
      <span v-if="lang !== 'text'" class="tux-codeblock__lang">{{ lang }}</span>
    </figcaption>

    <div class="tux-codeblock__body">
      <div v-if="!noCopy || !noDownload" class="tux-codeblock__actions">
        <button
          v-if="!noDownload"
          type="button"
          class="tux-codeblock__action"
          :aria-label="`Download ${resolvedDownloadName}`"
          @click="download"
        >
          <Icon name="lucide:download" class="tux-codeblock__action-icon" />
          <span>Download</span>
        </button>
        <button
          v-if="!noCopy"
          type="button"
          class="tux-codeblock__action"
          :aria-label="copied ? 'Copied' : 'Copy code'"
          @click="copy"
        >
          <Icon
            :name="copied ? 'lucide:check' : 'lucide:copy'"
            class="tux-codeblock__action-icon"
          />
          <span>{{ copied ? "Copied" : "Copy" }}</span>
        </button>
      </div>

      <!-- Highlighted output once Shiki has loaded. v-html is safe
           here: the source is Shiki's own escaped output (server-side
           rendered via useTuxHighlighter), not user input. -->
      <!-- eslint-disable-next-line vue/no-v-html -->
      <div v-if="highlightedCode" class="tux-codeblock__rendered" v-html="highlightedCode" />

      <!-- Line-numbered fallback (or text-mode source) -->
      <pre v-else class="tux-codeblock__fallback"><code><span
        v-for="(line, i) in lines"
        :key="i"
        class="tux-codeblock__line"
      ><span
        v-if="lineNumbers"
        class="tux-codeblock__line-no"
        aria-hidden="true"
      >{{ i + 1 }}</span><span>{{ line }}
</span></span></code></pre>
    </div>
  </figure>
</template>

<style scoped>
.tux-codeblock {
  container-type: inline-size;
  container-name: tux-codeblock;
  margin: 1.25rem 0;
  border: 1px solid var(--surface-border);
  border-radius: var(--radius-md);
  background: var(--surface-raised);
  overflow: hidden;
}

.tux-codeblock__caption {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.75rem;
  padding: 0.5rem 0.875rem;
  background: var(--surface-sunken);
  border-bottom: 1px solid var(--surface-border);
  font-family: var(--font-mono);
  font-size: 0.75rem;
}

.tux-codeblock__filename {
  color: var(--text-secondary);
  font-weight: 500;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  min-width: 0;
}

.tux-codeblock__lang {
  flex-shrink: 0;
  font-size: 0.6875rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: var(--brand-primary);
}

.tux-codeblock__body {
  position: relative;
}

.tux-codeblock__actions {
  position: absolute;
  top: 0.5rem;
  right: 0.5rem;
  z-index: 2;
  display: inline-flex;
  align-items: center;
  gap: 0.375rem;
  opacity: 0;
  transition: opacity 0.15s ease;
}

.tux-codeblock:hover .tux-codeblock__actions,
.tux-codeblock:focus-within .tux-codeblock__actions {
  opacity: 1;
}

.tux-codeblock__action {
  display: inline-flex;
  align-items: center;
  gap: 0.375rem;
  padding: 0.375rem 0.625rem;
  font-family: var(--font-bold);
  font-size: 0.6875rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: var(--text-secondary);
  background: var(--surface-page);
  border: 1px solid var(--surface-border);
  border-radius: var(--radius-sm);
  cursor: pointer;
  transition: color 0.15s ease, border-color 0.15s ease;
}

.tux-codeblock__action:hover,
.tux-codeblock__action:focus-visible {
  color: var(--brand-primary);
  border-color: color-mix(in srgb, var(--brand-primary) 40%, var(--surface-border));
  outline: none;
}

.tux-codeblock__action-icon {
  width: 0.8125rem;
  height: 0.8125rem;
}

/* Shiki-rendered output. The `:deep(pre)` reaches into the
   highlighter's HTML to apply our padding/scroll/font conventions. */
.tux-codeblock__rendered :deep(pre) {
  margin: 0;
  padding: 1rem 1.125rem;
  font-family: var(--font-mono);
  font-size: 0.8125rem;
  line-height: 1.6;
  overflow-x: auto;
}

.tux-codeblock__rendered :deep(code) {
  font-family: var(--font-mono);
}

/* Plain-text / pre-Shiki fallback */
.tux-codeblock__fallback {
  margin: 0;
  padding: 1rem 1.125rem;
  font-family: var(--font-mono);
  font-size: 0.8125rem;
  line-height: 1.6;
  color: var(--text-primary);
  overflow-x: auto;
  background: transparent;
}

.tux-codeblock__line {
  display: block;
  white-space: pre;
}

.tux-codeblock__line-no {
  display: inline-block;
  width: 2.5rem;
  margin-right: 1rem;
  text-align: right;
  color: var(--text-muted);
  user-select: none;
  font-variant-numeric: tabular-nums;
}

/* Line-numbered Shiki output — apply gutter via deep selector. */
.tux-codeblock--with-lines .tux-codeblock__rendered :deep(pre code) {
  counter-reset: tux-line;
}

.tux-codeblock--with-lines .tux-codeblock__rendered :deep(.line) {
  counter-increment: tux-line;
}

.tux-codeblock--with-lines .tux-codeblock__rendered :deep(.line)::before {
  content: counter(tux-line);
  display: inline-block;
  width: 2.25rem;
  margin-right: 1rem;
  text-align: right;
  color: var(--text-muted);
  font-variant-numeric: tabular-nums;
}
</style>
